version: 5.1.0
variant: default
logo: /images/logo.gif
head:
    favicon: /images/logo.ico
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: /
        归档: /archives
        类别: /categories
        标签: /tags
        关于: /about
        访问统计: https://tongji.baidu.com/web/welcome/ico?s=8c2572cbfe4082d1fcd1327e4614cf34
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Contact me:
            icon: far fa-envelope
            url: mailto:ChnMig@Outlook.com
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ChnMig
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: auto
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: ChnMig
        author_title: 知识,实践,灵感和机遇
        location: 江苏苏州
        avatar: /images/logo.gif
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/ChnMig
        social_links:
            Email:
                icon: far fa-envelope
                url: mailto:ChnMig@Outlook.com
            Github:
                icon: fab fa-github
                url: https://github.com/ppoffice
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Hexo: https://hexo.io
            Icarus: https://github.com/ppoffice/hexo-theme-icarus
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: left
        type: tags
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 8c2572cbfe4082d1fcd1327e4614cf34
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    katex: true
    mathjax: true
    outdated_browser: true
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
